name: MineMint
version: '${project.version}'
main: com.mbms.minemint.MineMint
api-version: 1.18
description: Web3 + Minecraft = <3
commands:
  ignite:
    description: This command ignites a player.
    usage: /<command> [player]
    permission: default.ignite
  home:
    description: Home commands list
    usage: /<command> <sub command> <name>
    permission: default.home
  mint:
    description: This command opens minting menu.
    usage: /<command>
    permission: default.mint
  nasa:
    description: This command gets data from NASA.
    usage: /<command>
    permission: default.nasa
  greet:
    description: This command greets a player.
    usage: /<command>
    permission: default.greet
permissions:
  default:
    description: Basic permissions for the server.
    default: true
    children:
      default.ignite: true
      default.home: true
      default.mint: true
      default.nasa: true
      default.greet: true
